server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/branium-academy/api/v1}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:be-branium-academy}
  datasource:
    url: ${DATASOURCE_URL:jdbc:oracle:thin:@//localhost:1521/ORCLPDB1}
    username: ${DATASOURCE_USERNAME:han_branium_academy}
    password: ${DATASOURCE_PASSWORD:Sohappy212}
  jpa:
    database: oracle
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: hntrnn12@gmail.com
    password: lorhzfhafcgoalnz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secret-key: 78040db429b610814e9f299ef8590b28be75aeacd9ff1f3e53bc8b72f4c0c88c
  valid-access-token-time: 3600
  valid-refresh-token-time: 7200
stripe:
  publishable-key: pk_test_51Q2psLDmtILFtFXB2Eq86fYiljYg7nVkcdtKXUBr04obrVebQPBCJDwhIXVuS29IHLDZlidi9SzrT6HRLg0oKXJi00l1cab1Xk
  secret-key: sk_test_51Q2psLDmtILFtFXBrBDezDUOCI1ptshMVrd69SUafboSO0tlMeAOiQowE06xoe3s7sxgC5S1ULVFlEoRlzzuForx00oo0xZWYG


