server:
  port: ${PORT:8080}
  servlet:
    context-path: /branium-academy/api/v1
spring:
  application:
    name: be-branium-academy
  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@//localhost:1521/orclpdb}
    username: ${DATABASE_USERNAME:han_branium_academy}
    password: ${DATABASE_PASSWORD:Sohappy212}
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
logging:
  level:
   org.springframework.security: trace
jwt:
  secret-key: 78040db429b610814e9f299ef8590b28be75aeacd9ff1f3e53bc8b72f4c0c88c
  valid-access-token-time: 3600
  valid-refresh-token-time: 7200

