server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/branium-academy/api/v1}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:be-branium-academy}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0}
    username: ${DATASOURCE_USERNAME:postgres.vofzighecqfnrmdsiwap}
    password: ${DATASOURCE_PASSWORD:Sohappy2122003@}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: hntrnn12@gmail.com
    password: nfzsrfbrqhmtcayu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
jwt:
  secret-key: 78040db429b610814e9f299ef8590b28be75aeacd9ff1f3e53bc8b72f4c0c88c
  valid-access-token-time: 3600
  valid-refresh-token-time: 7200
stripe:
  publishable-key: pk_test_51Q2psLDmtILFtFXB2Eq86fYiljYg7nVkcdtKXUBr04obrVebQPBCJDwhIXVuS29IHLDZlidi9SzrT6HRLg0oKXJi00l1cab1Xk
  secret-key: sk_test_51Q2psLDmtILFtFXBrBDezDUOCI1ptshMVrd69SUafboSO0tlMeAOiQowE06xoe3s7sxgC5S1ULVFlEoRlzzuForx00oo0xZWYG

